[package]
name = "datagen"
version = "0.1.0"
edition = "2024"

[dependencies]
cold-clear = { git = "https://github.com/MinusKelvin/cold-clear", rev = "279edd7" }
libtetris = { git = "https://github.com/MinusKelvin/cold-clear", rev = "279edd7" }
rand = "0.7.0"
rand_pcg = "0.2.1"
