[package]
name = "play"
version = "0.1.0"
edition = "2024"

[dependencies]
ort = "=2.0.0-rc.10"
libtetris = { git = "https://github.com/MinusKelvin/cold-clear", rev = "279edd7" }
ndarray = "0.16.1"
rand = "0.7.0"
