[package]
name = "nn-encoding"
version = "0.1.0"
edition = "2024"

[dependencies]
libtetris = { git = "https://github.com/MinusKelvin/cold-clear", rev = "279edd7" }
ndarray = "0.16.1"
num-traits = "0.2.19"
